
x-db-config: &db-config
  DB_URL_ASYNC: "${DB_URL_ASYNC:-postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}}"
  DB_URL_SYNC: "${DB_URL_SYNC:-postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}}"

x-aws-config: &aws-config
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_S3_BUCKET: "bucket-1"
  AWS_COGNITO_POOL: "pool-1"
  AWS_COGNITO_POOL_CLIENT: "client-1"
  AWS_SQS_QUEUE: &sqs-queue "queue-1"


x-celery-config: &celery-config
  CELERY_BROKER_URL: "sqs://test:test@localstack:4566"
  CELERY_BROKER_TRANSPORT_OPTIONS__predefined_queues__queue-1__url: 'http://sqs.us-east-1.localstack:4566/000000000000/queue-1'
  CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND:-db+${DB_URL_SYNC}}"
  CELERY_DEFAULT_QUEUE: *sqs-queue

x-app-common: &app-common
  build:
    context: .
    dockerfile: infra/application/Dockerfile
  depends_on:
    - postgres
    - localstack
  environment:
    <<: [ *db-config, *aws-config,  *celery-config ]
  extra_hosts:
    - 'localstack:192.168.28.10'
    - 'sqs.us-east-1.localstack:192.168.28.10'
    - 'postgres:192.168.28.5'

services:
  app:
    <<: *app-common
    container_name: app
    command: uvicorn src.application:app --host 0.0.0.0 --port 8000 ${ADDITIONAL_UVICORN_CMD:-}
    volumes:
      - ${LDE_VOLUME:-data:/data}
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - internal
      - external
  celery:
    <<: *app-common
    command: celery -A src.application.core worker -Q "queue-1"  --loglevel=INFO
    container_name: celery
    depends_on:
      - app
    networks:
      - internal

  localstack:
    image: localstack/localstack-pro:latest
    container_name: aws
    environment:
      <<: *aws-config
      SERVICES: s3,cognito-idp,sqs
      LOCALSTACK_AUTH_TOKEN: "${LOCALSTACK_AUTH_TOKEN}"
      USE_SINGLE_REGION: 1
      SMTP_HOST: "${SMTP_HOST:-}"
      SMTP_PASS: "${SMTP_PASS:-}"
      SMTP_USER: "${SMTP_USER:-}"
      SMTP_EMAIL: "${SMTP_USER:-}"
      LOCALSTACK_HOST: 'localstack:4566'
      DEBUG: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./infra/localstack/ready.d:/etc/localstack/init/ready.d"
    networks:
      internal:
        ipv4_address: ${LOCALSTACK_IP:-192.168.28.10}

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      internal:
        ipv4_address: ${DB_IP:-192.168.28.5}

volumes:
  data:

networks:
  external:
  internal:
    ipam:
      config:
        - subnet: 192.168.28.0/24

